title: It's a Blog!
owner: Sathvik Udupa
email: sathvikudupa66@gmail.com
description: A blog exists
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username: "SathvikUdupa"
github_username: "bloodraven66"
disqus_username: 
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
